2024-11-25 23:31:53: CRITICAL [users_model.py:20] MongoDB environment variables are required
2024-11-25 23:32:08: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-25 23:32:08: INFO [_internal.py:97] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-11-25 23:32:08: INFO [_internal.py:97] [33mPress CTRL+C to quit[0m
2024-11-25 23:32:08: INFO [_internal.py:97]  * Restarting with stat
2024-11-25 23:32:08: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-25 23:32:08: WARNING [_internal.py:97]  * Debugger is active!
2024-11-25 23:32:08: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-25 23:37:56: ERROR [logger_base.py:29] Error fetching the request data: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
2024-11-25 23:37:56: ERROR [logger_base.py:29] Error creating new user: Error fetching the request data: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
2024-11-25 23:37:56: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:37:56] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 500 -
2024-11-25 23:38:18: ERROR [logger_base.py:29] Error fetching the request data: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
2024-11-25 23:38:18: ERROR [logger_base.py:29] Error creating new user: Error fetching the request data: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
2024-11-25 23:38:18: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:38:18] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 500 -
2024-11-25 23:38:51: ERROR [logger_base.py:29] Error fetching the request data: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
2024-11-25 23:38:51: ERROR [logger_base.py:29] Error: Error fetching the request data: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
2024-11-25 23:38:51: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:38:51] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 500 -
2024-11-25 23:40:39: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-25 23:40:39: INFO [users_model.py:58] MongoDB connection closed
2024-11-25 23:40:40: INFO [_internal.py:97]  * Restarting with stat
2024-11-25 23:40:40: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-25 23:40:40: WARNING [_internal.py:97]  * Debugger is active!
2024-11-25 23:40:40: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-25 23:41:38: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:41:38] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-25 23:41:38: ERROR [logger_base.py:29] Invalid user data: Password should have at least one uppercase letter
2024-11-25 23:41:38: ERROR [logger_base.py:29] Error: Invalid user data: Password should have at least one uppercase letter
2024-11-25 23:41:38: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:41:38] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-25 23:41:56: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:41:56] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-25 23:41:56: ERROR [logger_base.py:29] Invalid user data: The user type is not valid
2024-11-25 23:41:56: ERROR [logger_base.py:29] Error: Invalid user data: The user type is not valid
2024-11-25 23:41:56: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:41:56] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-25 23:42:11: INFO [users_model.py:58] MongoDB connection closed
2024-11-25 23:42:12: INFO [users_model.py:58] MongoDB connection closed
2024-11-25 23:42:13: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-25 23:42:13: INFO [_internal.py:97] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-11-25 23:42:13: INFO [_internal.py:97] [33mPress CTRL+C to quit[0m
2024-11-25 23:42:13: INFO [_internal.py:97]  * Restarting with stat
2024-11-25 23:42:13: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-25 23:42:13: WARNING [_internal.py:97]  * Debugger is active!
2024-11-25 23:42:13: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-25 23:42:55: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-25 23:42:55: INFO [users_model.py:58] MongoDB connection closed
2024-11-25 23:42:55: INFO [_internal.py:97]  * Restarting with stat
2024-11-25 23:42:56: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-25 23:42:56: WARNING [_internal.py:97]  * Debugger is active!
2024-11-25 23:42:56: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-25 23:42:59: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:42:59] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-25 23:42:59: ERROR [logger_base.py:29] Invalid user data: The user type is not valid
2024-11-25 23:42:59: ERROR [logger_base.py:29] Error: Invalid user data: The user type is not valid
2024-11-25 23:42:59: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:42:59] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-25 23:43:29: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-25 23:43:29: INFO [users_model.py:58] MongoDB connection closed
2024-11-25 23:43:30: INFO [_internal.py:97]  * Restarting with stat
2024-11-25 23:43:30: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-25 23:43:30: WARNING [_internal.py:97]  * Debugger is active!
2024-11-25 23:43:30: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-25 23:43:34: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:43:34] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-25 23:43:35: ERROR [logger_base.py:29] Error: No user with the entered data was found.
2024-11-25 23:43:35: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:43:35] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 500 -
2024-11-25 23:44:03: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:44:03] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-25 23:44:03: INFO [users_routes.py:176] Login user: {'_id': 18, 'email': 'pablo8@test.com', 'password': '6ea1634442bf3a853f350c0d5612742c99646d8ca922ea942382ba152b51f077', 'type': 'admin', 'status': 'active'}
2024-11-25 23:44:03: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:44:03] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 201 -
2024-11-25 23:45:22: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:45:22] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-25 23:45:22: INFO [users_routes.py:176] Login user: {'_id': 18, 'email': 'pablo8@test.com', 'password': '6ea1634442bf3a853f350c0d5612742c99646d8ca922ea942382ba152b51f077', 'type': 'admin', 'status': 'active'}
2024-11-25 23:45:22: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:45:22] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 201 -
2024-11-25 23:46:16: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:46:16] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-25 23:46:16: INFO [users_routes.py:176] Login user: {'_id': 19, 'email': 'pablo9@test.com', 'password': '6ea1634442bf3a853f350c0d5612742c99646d8ca922ea942382ba152b51f077', 'type': 'admin', 'status': 'active'}
2024-11-25 23:46:16: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:46:16] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 201 -
2024-11-25 23:48:29: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-25 23:48:29: INFO [users_model.py:58] MongoDB connection closed
2024-11-25 23:48:29: INFO [_internal.py:97]  * Restarting with stat
2024-11-25 23:48:29: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-25 23:48:29: WARNING [_internal.py:97]  * Debugger is active!
2024-11-25 23:48:29: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-25 23:48:33: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-25 23:48:33: INFO [users_model.py:58] MongoDB connection closed
2024-11-25 23:48:34: INFO [_internal.py:97]  * Restarting with stat
2024-11-25 23:48:34: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-25 23:48:34: WARNING [_internal.py:97]  * Debugger is active!
2024-11-25 23:48:34: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-25 23:48:36: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-25 23:48:36: INFO [users_model.py:58] MongoDB connection closed
2024-11-25 23:48:37: INFO [_internal.py:97]  * Restarting with stat
2024-11-25 23:48:37: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-25 23:48:37: WARNING [_internal.py:97]  * Debugger is active!
2024-11-25 23:48:37: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-25 23:48:41: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-25 23:48:41: INFO [users_model.py:58] MongoDB connection closed
2024-11-25 23:48:41: INFO [_internal.py:97]  * Restarting with stat
2024-11-25 23:48:42: INFO [users_model.py:58] MongoDB connection closed
2024-11-25 23:49:09: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-25 23:49:09: INFO [_internal.py:97] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-11-25 23:49:09: INFO [_internal.py:97] [33mPress CTRL+C to quit[0m
2024-11-25 23:49:09: INFO [_internal.py:97]  * Restarting with stat
2024-11-25 23:49:09: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-25 23:49:09: WARNING [_internal.py:97]  * Debugger is active!
2024-11-25 23:49:09: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-25 23:49:20: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:49:20] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-25 23:49:20: INFO [users_routes.py:176] Login user: {'_id': 19, 'email': 'pablo9@test.com', 'password': '6ea1634442bf3a853f350c0d5612742c99646d8ca922ea942382ba152b51f077', 'type': 'admin', 'status': 'active'}
2024-11-25 23:49:20: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:49:20] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 201 -
2024-11-25 23:49:52: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:49:52] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-25 23:49:52: INFO [users_routes.py:176] Login user: {'_id': 19, 'email': 'pablo9@test.com', 'password': '6ea1634442bf3a853f350c0d5612742c99646d8ca922ea942382ba152b51f077', 'type': 'admin', 'status': 'active'}
2024-11-25 23:49:52: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:49:52] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 201 -
2024-11-25 23:49:59: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:49:59] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-25 23:49:59: INFO [users_routes.py:176] Login user: {'_id': 19, 'email': 'pablo9@test.com', 'password': '6ea1634442bf3a853f350c0d5612742c99646d8ca922ea942382ba152b51f077', 'type': 'admin', 'status': 'active'}
2024-11-25 23:49:59: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:49:59] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 201 -
2024-11-25 23:50:00: INFO [users_routes.py:176] Login user: {'_id': 19, 'email': 'pablo9@test.com', 'password': '6ea1634442bf3a853f350c0d5612742c99646d8ca922ea942382ba152b51f077', 'type': 'admin', 'status': 'active'}
2024-11-25 23:50:00: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:50:00] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 201 -
2024-11-25 23:50:00: INFO [users_routes.py:176] Login user: {'_id': 19, 'email': 'pablo9@test.com', 'password': '6ea1634442bf3a853f350c0d5612742c99646d8ca922ea942382ba152b51f077', 'type': 'admin', 'status': 'active'}
2024-11-25 23:50:00: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:50:00] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 201 -
2024-11-25 23:50:01: INFO [users_routes.py:176] Login user: {'_id': 19, 'email': 'pablo9@test.com', 'password': '6ea1634442bf3a853f350c0d5612742c99646d8ca922ea942382ba152b51f077', 'type': 'admin', 'status': 'active'}
2024-11-25 23:50:01: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:50:01] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 201 -
2024-11-25 23:52:41: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:52:41] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-25 23:52:41: INFO [users_routes.py:176] Login user: {'_id': 19, 'email': 'pablo9@test.com', 'password': '6ea1634442bf3a853f350c0d5612742c99646d8ca922ea942382ba152b51f077', 'type': 'admin', 'status': 'active'}
2024-11-25 23:52:41: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:52:41] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 201 -
2024-11-25 23:53:11: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:53:11] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-25 23:53:11: INFO [users_routes.py:176] Login user: {'_id': 19, 'email': 'pablo9@test.com', 'password': '6ea1634442bf3a853f350c0d5612742c99646d8ca922ea942382ba152b51f077', 'type': 'client', 'status': 'active'}
2024-11-25 23:53:11: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:53:11] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 201 -
2024-11-25 23:53:18: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:53:18] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-25 23:53:18: ERROR [logger_base.py:29] Error: No user with the entered data was found.
2024-11-25 23:53:18: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:53:18] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 500 -
2024-11-25 23:55:09: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:55:09] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-25 23:55:09: ERROR [logger_base.py:29] Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-25 23:55:09: ERROR [logger_base.py:29] Error: Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-25 23:55:09: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:55:09] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-25 23:55:33: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:55:33] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-25 23:55:33: ERROR [logger_base.py:29] Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-25 23:55:33: ERROR [logger_base.py:29] Error: Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-25 23:55:33: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:55:33] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-25 23:55:35: ERROR [logger_base.py:29] Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-25 23:55:35: ERROR [logger_base.py:29] Error: Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-25 23:55:35: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:55:35] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-25 23:55:38: ERROR [logger_base.py:29] Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-25 23:55:38: ERROR [logger_base.py:29] Error: Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-25 23:55:38: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:55:38] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-25 23:55:53: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:55:53] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-25 23:55:53: ERROR [logger_base.py:29] Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-25 23:55:53: ERROR [logger_base.py:29] Error: Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-25 23:55:53: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:55:53] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-25 23:59:29: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:59:29] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-25 23:59:29: ERROR [logger_base.py:29] Invalid user data: User password must have at least 8 characters
2024-11-25 23:59:29: ERROR [logger_base.py:29] Error: Invalid user data: User password must have at least 8 characters
2024-11-25 23:59:29: INFO [_internal.py:97] 127.0.0.1 - - [25/Nov/2024 23:59:29] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-26 00:01:03: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:01:03] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:01:03: ERROR [logger_base.py:29] Invalid user data: Password should have at least one numeral
2024-11-26 00:01:03: ERROR [logger_base.py:29] Error: Invalid user data: Password should have at least one numeral
2024-11-26 00:01:03: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:01:03] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-26 00:02:13: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:02:13] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:02:13: ERROR [logger_base.py:29] Invalid user data: Password should have at least one numeral
2024-11-26 00:02:13: ERROR [logger_base.py:29] Error: Invalid user data: Password should have at least one numeral
2024-11-26 00:02:13: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:02:13] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-26 00:02:21: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:02:21] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:02:21: ERROR [logger_base.py:29] Invalid user data: Password should have at least one numeral
2024-11-26 00:02:21: ERROR [logger_base.py:29] Error: Invalid user data: Password should have at least one numeral
2024-11-26 00:02:21: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:02:21] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-26 00:02:26: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:02:26] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:02:26: ERROR [logger_base.py:29] Invalid user data: Password should have at least one numeral
2024-11-26 00:02:26: ERROR [logger_base.py:29] Error: Invalid user data: Password should have at least one numeral
2024-11-26 00:02:26: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:02:26] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-26 00:03:16: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:03:16] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:03:16: ERROR [logger_base.py:29] Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:03:16: ERROR [logger_base.py:29] Error: Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:03:16: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:03:16] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-26 00:03:30: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:03:30] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:03:30: ERROR [logger_base.py:29] Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:03:30: ERROR [logger_base.py:29] Error: Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:03:30: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:03:30] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-26 00:03:32: ERROR [logger_base.py:29] Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:03:32: ERROR [logger_base.py:29] Error: Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:03:32: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:03:32] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-26 00:03:32: ERROR [logger_base.py:29] Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:03:32: ERROR [logger_base.py:29] Error: Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:03:32: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:03:32] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-26 00:03:39: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:03:39] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:03:39: ERROR [logger_base.py:29] Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:03:39: ERROR [logger_base.py:29] Error: Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:03:39: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:03:39] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-26 00:05:03: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:05:03] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:05:03: ERROR [logger_base.py:29] Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:05:03: ERROR [logger_base.py:29] Error: Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:05:03: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:05:03] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-26 00:05:33: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:05:33] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:05:33: ERROR [logger_base.py:29] Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:05:33: ERROR [logger_base.py:29] Error: Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:05:33: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:05:33] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-26 00:06:00: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:06:00] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:06:00: ERROR [logger_base.py:29] Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:06:00: ERROR [logger_base.py:29] Error: Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:06:00: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:06:00] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-26 00:06:20: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:06:20] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:06:20: ERROR [logger_base.py:29] Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:06:20: ERROR [logger_base.py:29] Error: Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:06:20: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:06:20] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-26 00:06:48: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:06:48] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:06:48: ERROR [logger_base.py:29] Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:06:48: ERROR [logger_base.py:29] Error: Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:06:48: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:06:48] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-26 00:07:11: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:07:11] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:07:11: ERROR [logger_base.py:29] Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:07:11: ERROR [logger_base.py:29] Error: Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:07:11: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:07:11] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-26 00:07:16: ERROR [logger_base.py:29] Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:07:16: ERROR [logger_base.py:29] Error: Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:07:16: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:07:16] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-26 00:07:20: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:07:20] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:07:20: ERROR [logger_base.py:29] Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:07:20: ERROR [logger_base.py:29] Error: Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:07:20: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:07:20] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-26 00:07:27: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:07:27] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:07:28: ERROR [logger_base.py:29] Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:07:28: ERROR [logger_base.py:29] Error: Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:07:28: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:07:28] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-26 00:07:31: ERROR [logger_base.py:29] Invalid user data: User password must have at least 8 characters
2024-11-26 00:07:31: ERROR [logger_base.py:29] Error: Invalid user data: User password must have at least 8 characters
2024-11-26 00:07:31: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:07:31] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-26 00:07:36: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:07:36] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:07:36: ERROR [logger_base.py:29] Invalid user data: Password should have at least one uppercase letter
2024-11-26 00:07:36: ERROR [logger_base.py:29] Error: Invalid user data: Password should have at least one uppercase letter
2024-11-26 00:07:36: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:07:36] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-26 00:07:41: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:07:41] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:07:41: ERROR [logger_base.py:29] Error: No user with the entered data was found.
2024-11-26 00:07:41: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:07:41] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 500 -
2024-11-26 00:07:58: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:07:58] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:07:58: INFO [users_routes.py:176] Login user: {'_id': 19, 'email': 'pablo9@test.com', 'password': '6ea1634442bf3a853f350c0d5612742c99646d8ca922ea942382ba152b51f077', 'type': 'client', 'status': 'active'}
2024-11-26 00:07:58: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:07:58] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 201 -
2024-11-26 00:08:29: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:08:29] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:08:29: ERROR [logger_base.py:29] Invalid user data: User password must have at least 8 characters
2024-11-26 00:08:29: ERROR [logger_base.py:29] Error: Invalid user data: User password must have at least 8 characters
2024-11-26 00:08:29: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:08:29] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-26 00:08:34: ERROR [logger_base.py:29] Invalid user data: Password should have at least one uppercase letter
2024-11-26 00:08:34: ERROR [logger_base.py:29] Error: Invalid user data: Password should have at least one uppercase letter
2024-11-26 00:08:34: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:08:34] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-26 00:08:37: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:08:37] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:08:37: ERROR [logger_base.py:29] Invalid user data: Password should have at least one uppercase letter
2024-11-26 00:08:37: ERROR [logger_base.py:29] Error: Invalid user data: Password should have at least one uppercase letter
2024-11-26 00:08:37: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:08:37] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-26 00:08:38: ERROR [logger_base.py:29] Error: No user with the entered data was found.
2024-11-26 00:08:38: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:08:38] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 500 -
2024-11-26 00:09:11: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:09:11] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:09:11: ERROR [logger_base.py:29] Error: No user with the entered data was found.
2024-11-26 00:09:11: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:09:11] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 500 -
2024-11-26 00:09:15: INFO [users_routes.py:176] Login user: {'_id': 19, 'email': 'pablo9@test.com', 'password': '6ea1634442bf3a853f350c0d5612742c99646d8ca922ea942382ba152b51f077', 'type': 'client', 'status': 'active'}
2024-11-26 00:09:15: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:09:15] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 201 -
2024-11-26 00:09:32: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:09:32] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:09:32: INFO [users_routes.py:176] Login user: {'_id': 19, 'email': 'pablo9@test.com', 'password': '6ea1634442bf3a853f350c0d5612742c99646d8ca922ea942382ba152b51f077', 'type': 'client', 'status': 'active'}
2024-11-26 00:09:32: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:09:32] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 201 -
2024-11-26 00:11:45: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:11:45] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:11:45: INFO [users_routes.py:176] Login user: {'_id': 19, 'email': 'pablo9@test.com', 'password': '6ea1634442bf3a853f350c0d5612742c99646d8ca922ea942382ba152b51f077', 'type': 'client', 'status': 'active'}
2024-11-26 00:11:45: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:11:45] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 201 -
2024-11-26 00:12:43: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:12:43] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:12:43: INFO [users_routes.py:176] Login user: {'_id': 19, 'email': 'pablo9@test.com', 'password': '6ea1634442bf3a853f350c0d5612742c99646d8ca922ea942382ba152b51f077', 'type': 'client', 'status': 'active'}
2024-11-26 00:12:43: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:12:43] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 201 -
2024-11-26 00:13:32: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:13:32] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:13:32: INFO [users_routes.py:176] Login user: {'_id': 19, 'email': 'pablo9@test.com', 'password': '6ea1634442bf3a853f350c0d5612742c99646d8ca922ea942382ba152b51f077', 'type': 'client', 'status': 'active'}
2024-11-26 00:13:32: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:13:32] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 201 -
2024-11-26 00:13:57: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:13:57] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:13:57: INFO [users_routes.py:176] Login user: {'_id': 19, 'email': 'pablo9@test.com', 'password': '6ea1634442bf3a853f350c0d5612742c99646d8ca922ea942382ba152b51f077', 'type': 'admin', 'status': 'active'}
2024-11-26 00:13:57: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:13:57] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 201 -
2024-11-26 00:15:04: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:15:04] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:15:04: INFO [users_routes.py:176] Login user: {'_id': 19, 'email': 'pablo9@test.com', 'password': '6ea1634442bf3a853f350c0d5612742c99646d8ca922ea942382ba152b51f077', 'type': 'admin', 'status': 'active'}
2024-11-26 00:15:04: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:15:04] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 201 -
2024-11-26 00:15:07: ERROR [logger_base.py:29] Error: Please verify the data entered (email and password)
2024-11-26 00:15:07: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:15:07] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 500 -
2024-11-26 00:15:14: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:15:14] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:15:14: INFO [users_routes.py:176] Login user: {'_id': 19, 'email': 'pablo9@test.com', 'password': '6ea1634442bf3a853f350c0d5612742c99646d8ca922ea942382ba152b51f077', 'type': 'admin', 'status': 'active'}
2024-11-26 00:15:14: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:15:14] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 201 -
2024-11-26 00:19:50: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-26 00:19:50: INFO [users_model.py:58] MongoDB connection closed
2024-11-26 00:19:51: INFO [_internal.py:97]  * Restarting with stat
2024-11-26 00:19:51: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-26 00:19:51: WARNING [_internal.py:97]  * Debugger is active!
2024-11-26 00:19:51: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-26 00:19:54: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-26 00:19:54: INFO [users_model.py:58] MongoDB connection closed
2024-11-26 00:19:55: INFO [_internal.py:97]  * Restarting with stat
2024-11-26 00:19:55: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-26 00:19:55: WARNING [_internal.py:97]  * Debugger is active!
2024-11-26 00:19:55: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-26 00:19:56: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-26 00:19:56: INFO [users_model.py:58] MongoDB connection closed
2024-11-26 00:19:56: INFO [_internal.py:97]  * Restarting with stat
2024-11-26 00:19:57: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-26 00:19:57: WARNING [_internal.py:97]  * Debugger is active!
2024-11-26 00:19:57: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-26 00:25:48: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:25:48] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:25:48: ERROR [logger_base.py:29] Invalid user data: User password must have at least 8 characters
2024-11-26 00:25:48: ERROR [logger_base.py:29] Error creating new user: Invalid user data: User password must have at least 8 characters
2024-11-26 00:25:48: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:25:48] "[31m[1mPOST /api/v1/users HTTP/1.1[0m" 400 -
2024-11-26 00:26:01: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:26:01] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:26:01: ERROR [logger_base.py:29] Invalid user data: User password must have at least 8 characters
2024-11-26 00:26:01: ERROR [logger_base.py:29] Error creating new user: Invalid user data: User password must have at least 8 characters
2024-11-26 00:26:01: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:26:01] "[31m[1mPOST /api/v1/users HTTP/1.1[0m" 400 -
2024-11-26 00:26:06: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:26:06] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:26:06: ERROR [logger_base.py:29] Invalid user data: User password must have at least 8 characters
2024-11-26 00:26:06: ERROR [logger_base.py:29] Error creating new user: Invalid user data: User password must have at least 8 characters
2024-11-26 00:26:06: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:26:06] "[31m[1mPOST /api/v1/users HTTP/1.1[0m" 400 -
2024-11-26 00:26:35: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:26:35] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:26:35: ERROR [logger_base.py:29] Invalid user data: User password must have at least 8 characters
2024-11-26 00:26:35: ERROR [logger_base.py:29] Error creating new user: Invalid user data: User password must have at least 8 characters
2024-11-26 00:26:35: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:26:35] "[31m[1mPOST /api/v1/users HTTP/1.1[0m" 400 -
2024-11-26 00:26:53: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-26 00:26:53: INFO [users_model.py:58] MongoDB connection closed
2024-11-26 00:26:54: INFO [_internal.py:97]  * Restarting with stat
2024-11-26 00:26:54: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-26 00:26:54: WARNING [_internal.py:97]  * Debugger is active!
2024-11-26 00:26:54: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-26 00:27:03: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-26 00:27:03: INFO [users_model.py:58] MongoDB connection closed
2024-11-26 00:27:03: INFO [_internal.py:97]  * Restarting with stat
2024-11-26 00:27:04: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-26 00:27:04: WARNING [_internal.py:97]  * Debugger is active!
2024-11-26 00:27:04: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-26 00:27:05: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-26 00:27:05: INFO [users_model.py:58] MongoDB connection closed
2024-11-26 00:27:05: INFO [_internal.py:97]  * Restarting with stat
2024-11-26 00:27:05: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-26 00:27:05: WARNING [_internal.py:97]  * Debugger is active!
2024-11-26 00:27:05: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-26 00:27:06: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-26 00:27:06: INFO [users_model.py:58] MongoDB connection closed
2024-11-26 00:27:07: INFO [_internal.py:97]  * Restarting with stat
2024-11-26 00:27:07: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-26 00:27:07: WARNING [_internal.py:97]  * Debugger is active!
2024-11-26 00:27:07: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-26 00:27:16: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-26 00:27:16: INFO [users_model.py:58] MongoDB connection closed
2024-11-26 00:27:17: INFO [_internal.py:97]  * Restarting with stat
2024-11-26 00:27:17: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-26 00:27:17: WARNING [_internal.py:97]  * Debugger is active!
2024-11-26 00:27:17: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-26 00:27:21: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:27:21] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:27:21: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:27:21] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 500 -
2024-11-26 00:27:47: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:27:47] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:27:47: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:27:47] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 500 -
2024-11-26 00:29:07: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:29:07] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:29:07: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:29:07] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 500 -
2024-11-26 00:29:54: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:29:54] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:29:54: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:29:54] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 500 -
2024-11-26 00:30:00: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:30:00] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:30:00: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:30:00] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 500 -
2024-11-26 00:30:01: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:30:01] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 500 -
2024-11-26 00:30:33: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-26 00:30:33: INFO [users_model.py:58] MongoDB connection closed
2024-11-26 00:30:34: INFO [_internal.py:97]  * Restarting with stat
2024-11-26 00:30:34: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-26 00:30:34: WARNING [_internal.py:97]  * Debugger is active!
2024-11-26 00:30:34: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-26 00:30:37: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-26 00:30:37: INFO [users_model.py:58] MongoDB connection closed
2024-11-26 00:30:38: INFO [_internal.py:97]  * Restarting with stat
2024-11-26 00:30:38: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-26 00:30:38: WARNING [_internal.py:97]  * Debugger is active!
2024-11-26 00:30:38: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-26 00:30:47: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-26 00:30:47: INFO [users_model.py:58] MongoDB connection closed
2024-11-26 00:30:47: INFO [_internal.py:97]  * Restarting with stat
2024-11-26 00:30:48: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-26 00:30:48: WARNING [_internal.py:97]  * Debugger is active!
2024-11-26 00:30:48: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-26 00:30:55: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-26 00:30:55: INFO [users_model.py:58] MongoDB connection closed
2024-11-26 00:30:55: INFO [_internal.py:97]  * Restarting with stat
2024-11-26 00:30:55: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-26 00:30:55: WARNING [_internal.py:97]  * Debugger is active!
2024-11-26 00:30:55: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-26 00:30:56: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-26 00:30:56: INFO [users_model.py:58] MongoDB connection closed
2024-11-26 00:30:57: INFO [_internal.py:97]  * Restarting with stat
2024-11-26 00:30:57: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-26 00:30:57: WARNING [_internal.py:97]  * Debugger is active!
2024-11-26 00:30:57: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-26 00:30:58: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-26 00:30:58: INFO [users_model.py:58] MongoDB connection closed
2024-11-26 00:30:59: INFO [_internal.py:97]  * Restarting with stat
2024-11-26 00:30:59: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-26 00:30:59: WARNING [_internal.py:97]  * Debugger is active!
2024-11-26 00:30:59: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-26 00:31:01: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-26 00:31:01: INFO [users_model.py:58] MongoDB connection closed
2024-11-26 00:31:01: INFO [_internal.py:97]  * Restarting with stat
2024-11-26 00:31:02: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-26 00:31:02: WARNING [_internal.py:97]  * Debugger is active!
2024-11-26 00:31:02: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-26 00:31:04: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:31:04] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:31:04: ERROR [logger_base.py:29] Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:31:04: ERROR [logger_base.py:29] Error creating new user: Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:31:04: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:31:04] "[31m[1mPOST /api/v1/users HTTP/1.1[0m" 400 -
2024-11-26 00:31:24: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:31:24] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:31:24: ERROR [logger_base.py:29] Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:31:24: ERROR [logger_base.py:29] Error creating new user: Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:31:24: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:31:24] "[31m[1mPOST /api/v1/users HTTP/1.1[0m" 400 -
2024-11-26 00:31:32: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-26 00:31:32: INFO [users_model.py:58] MongoDB connection closed
2024-11-26 00:31:32: INFO [_internal.py:97]  * Restarting with stat
2024-11-26 00:31:33: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-26 00:31:33: WARNING [_internal.py:97]  * Debugger is active!
2024-11-26 00:31:33: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-26 00:31:40: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:31:40] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:31:40: ERROR [logger_base.py:29] Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:31:40: ERROR [logger_base.py:29] Error creating new user: Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:31:40: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:31:40] "[31m[1mPOST /api/v1/users HTTP/1.1[0m" 400 -
2024-11-26 00:32:04: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-26 00:32:04: INFO [users_model.py:58] MongoDB connection closed
2024-11-26 00:32:04: INFO [_internal.py:97]  * Restarting with stat
2024-11-26 00:32:05: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-26 00:32:05: WARNING [_internal.py:97]  * Debugger is active!
2024-11-26 00:32:05: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-26 00:32:12: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:32:12] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:32:12: ERROR [logger_base.py:29] Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:32:12: ERROR [logger_base.py:29] Error creating new user: Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:32:12: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:32:12] "[31m[1mPOST /api/v1/users HTTP/1.1[0m" 400 -
2024-11-26 00:32:30: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:32:30] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:32:30: ERROR [logger_base.py:29] Invalid user data: Password should have at least one numeral
2024-11-26 00:32:30: ERROR [logger_base.py:29] Error creating new user: Invalid user data: Password should have at least one numeral
2024-11-26 00:32:30: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:32:30] "[31m[1mPOST /api/v1/users HTTP/1.1[0m" 400 -
2024-11-26 00:32:36: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:32:36] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:32:36: ERROR [logger_base.py:29] Invalid user data: Password should have at least one uppercase letter
2024-11-26 00:32:36: ERROR [logger_base.py:29] Error creating new user: Invalid user data: Password should have at least one uppercase letter
2024-11-26 00:32:36: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:32:36] "[31m[1mPOST /api/v1/users HTTP/1.1[0m" 400 -
2024-11-26 00:32:41: INFO [users_routes.py:276] New User created: {'email': 'asda@test.com', 'password': 'asdasfas1A', 'type': 'client', 'status': 'active', '_id': 20}
2024-11-26 00:32:41: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:32:41] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 201 -
2024-11-26 00:33:00: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:33:00] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:33:00: ERROR [logger_base.py:29] Error adding new user to database: Email is already registered
2024-11-26 00:33:00: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:33:00] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 500 -
2024-11-26 00:33:07: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:33:07] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:33:07: ERROR [logger_base.py:29] Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:33:07: ERROR [logger_base.py:29] Error creating new user: Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 00:33:07: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:33:07] "[31m[1mPOST /api/v1/users HTTP/1.1[0m" 400 -
2024-11-26 00:33:13: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:33:13] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:33:13: INFO [users_routes.py:276] New User created: {'email': 'asda1@test.com', 'password': 'asdasfas1A', 'type': 'client', 'status': 'active', '_id': 21}
2024-11-26 00:33:13: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:33:13] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 201 -
2024-11-26 00:34:18: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:34:18] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:34:18: ERROR [logger_base.py:29] Error adding new user to database: Email is already registered
2024-11-26 00:34:18: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:34:18] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 500 -
2024-11-26 00:34:22: INFO [users_routes.py:276] New User created: {'email': 'asda2@test.com', 'password': 'asdasfas1A', 'type': 'client', 'status': 'active', '_id': 22}
2024-11-26 00:34:22: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:34:22] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 201 -
2024-11-26 00:34:40: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:34:40] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:34:40: ERROR [logger_base.py:29] Error adding new user to database: Email is already registered
2024-11-26 00:34:40: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:34:40] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 500 -
2024-11-26 00:35:05: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:35:05] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:35:05: ERROR [logger_base.py:29] Invalid user data: Password should have at least one numeral
2024-11-26 00:35:05: ERROR [logger_base.py:29] Error creating new user: Invalid user data: Password should have at least one numeral
2024-11-26 00:35:05: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:35:05] "[31m[1mPOST /api/v1/users HTTP/1.1[0m" 400 -
2024-11-26 00:35:14: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:35:14] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:35:14: ERROR [logger_base.py:29] Invalid user data: Password should have at least one numeral
2024-11-26 00:35:14: ERROR [logger_base.py:29] Error creating new user: Invalid user data: Password should have at least one numeral
2024-11-26 00:35:14: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:35:14] "[31m[1mPOST /api/v1/users HTTP/1.1[0m" 400 -
2024-11-26 00:35:32: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:35:32] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:35:32: ERROR [logger_base.py:29] Invalid user data: Password should have at least one numeral
2024-11-26 00:35:32: ERROR [logger_base.py:29] Error creating new user: Invalid user data: Password should have at least one numeral
2024-11-26 00:35:32: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:35:32] "[31m[1mPOST /api/v1/users HTTP/1.1[0m" 400 -
2024-11-26 00:35:41: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:35:41] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:35:41: ERROR [logger_base.py:29] Invalid user data: Password should have at least one uppercase letter
2024-11-26 00:35:41: ERROR [logger_base.py:29] Error creating new user: Invalid user data: Password should have at least one uppercase letter
2024-11-26 00:35:41: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:35:41] "[31m[1mPOST /api/v1/users HTTP/1.1[0m" 400 -
2024-11-26 00:35:47: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:35:47] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:35:47: INFO [users_routes.py:276] New User created: {'email': 'sdfa@asdasda.comasd', 'password': 'response.datA1', 'type': 'client', 'status': 'active', '_id': 23}
2024-11-26 00:35:47: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:35:47] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 201 -
2024-11-26 00:37:18: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:37:18] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:37:18: INFO [users_routes.py:276] New User created: {'email': 'somw@test.com', 'password': 'response.datA1', 'type': 'client', 'status': 'active', '_id': 24}
2024-11-26 00:37:18: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:37:18] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 201 -
2024-11-26 00:37:45: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:37:45] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:37:45: ERROR [logger_base.py:29] Invalid user data: Password should have at least one numeral
2024-11-26 00:37:45: ERROR [logger_base.py:29] Error creating new user: Invalid user data: Password should have at least one numeral
2024-11-26 00:37:45: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:37:45] "[31m[1mPOST /api/v1/users HTTP/1.1[0m" 400 -
2024-11-26 00:37:52: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:37:52] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:37:52: INFO [users_routes.py:276] New User created: {'email': 'asdad@test.com', 'password': '"success"12A', 'type': 'client', 'status': 'active', '_id': 25}
2024-11-26 00:37:52: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:37:52] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 201 -
2024-11-26 00:38:32: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:38:32] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:38:32: ERROR [logger_base.py:29] Error adding new user to database: Email is already registered
2024-11-26 00:38:32: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:38:32] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 500 -
2024-11-26 00:38:36: INFO [users_routes.py:276] New User created: {'email': 'asdad1@test.com', 'password': '"success"12A', 'type': 'client', 'status': 'active', '_id': 26}
2024-11-26 00:38:36: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:38:36] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 201 -
2024-11-26 00:39:13: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:39:13] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:39:13: ERROR [logger_base.py:29] Error adding new user to database: Email is already registered
2024-11-26 00:39:13: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:39:13] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 500 -
2024-11-26 00:39:17: INFO [users_routes.py:276] New User created: {'email': 'asdad2@test.com', 'password': '"success"12A', 'type': 'client', 'status': 'active', '_id': 27}
2024-11-26 00:39:17: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:39:17] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 201 -
2024-11-26 00:39:51: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:39:51] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:39:51: INFO [users_routes.py:276] New User created: {'email': 'asda@teste.com', 'password': 'asdasd11A', 'type': 'client', 'status': 'active', '_id': 28}
2024-11-26 00:39:51: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:39:51] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 201 -
2024-11-26 00:42:30: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:42:30] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:42:30: ERROR [logger_base.py:29] Error adding new user to database: Email is already registered
2024-11-26 00:42:30: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:42:30] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 500 -
2024-11-26 00:42:34: INFO [users_routes.py:276] New User created: {'email': 'asda1@teste.com', 'password': 'asdasd11A', 'type': 'client', 'status': 'active', '_id': 29}
2024-11-26 00:42:34: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:42:34] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 201 -
2024-11-26 00:43:11: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:43:11] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:43:11: ERROR [logger_base.py:29] Error adding new user to database: Email is already registered
2024-11-26 00:43:11: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:43:11] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 500 -
2024-11-26 00:43:15: INFO [users_routes.py:276] New User created: {'email': 'asda2@teste.com', 'password': 'asdasd11A', 'type': 'client', 'status': 'active', '_id': 30}
2024-11-26 00:43:15: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:43:15] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 201 -
2024-11-26 00:43:47: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:43:47] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:43:47: ERROR [logger_base.py:29] Invalid user data: User password must have at least 8 characters
2024-11-26 00:43:47: ERROR [logger_base.py:29] Error creating new user: Invalid user data: User password must have at least 8 characters
2024-11-26 00:43:47: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:43:47] "[31m[1mPOST /api/v1/users HTTP/1.1[0m" 400 -
2024-11-26 00:43:57: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:43:57] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:43:57: ERROR [logger_base.py:29] Invalid user data: Password should have at least one numeral
2024-11-26 00:43:57: ERROR [logger_base.py:29] Error creating new user: Invalid user data: Password should have at least one numeral
2024-11-26 00:43:57: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:43:57] "[31m[1mPOST /api/v1/users HTTP/1.1[0m" 400 -
2024-11-26 00:44:02: ERROR [logger_base.py:29] Invalid user data: Password should have at least one uppercase letter
2024-11-26 00:44:02: ERROR [logger_base.py:29] Error creating new user: Invalid user data: Password should have at least one uppercase letter
2024-11-26 00:44:02: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:44:02] "[31m[1mPOST /api/v1/users HTTP/1.1[0m" 400 -
2024-11-26 00:44:06: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:44:06] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:44:06: INFO [users_routes.py:276] New User created: {'email': 'pablo@test.com', 'password': 'asdassdasd1S', 'type': 'client', 'status': 'active', '_id': 31}
2024-11-26 00:44:06: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:44:06] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 201 -
2024-11-26 00:44:28: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:44:28] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:44:28: ERROR [logger_base.py:29] Error adding new user to database: Email is already registered
2024-11-26 00:44:28: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:44:28] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 500 -
2024-11-26 00:51:06: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:51:06] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:51:06: INFO [users_routes.py:276] New User created: {'email': 'isarael@test.com', 'password': 'passWord123', 'type': 'client', 'status': 'active', '_id': 32}
2024-11-26 00:51:06: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:51:06] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 201 -
2024-11-26 00:52:07: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:52:07] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:52:07: ERROR [logger_base.py:29] Invalid user data: Password should have at least one numeral
2024-11-26 00:52:07: ERROR [logger_base.py:29] Error: Invalid user data: Password should have at least one numeral
2024-11-26 00:52:07: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:52:07] "[31m[1mPOST /api/v1/is-users HTTP/1.1[0m" 400 -
2024-11-26 00:52:31: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:52:31] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:52:31: INFO [users_routes.py:276] New User created: {'email': 'some1@test.com', 'password': 'editUserReq1', 'type': 'client', 'status': 'active', '_id': 33}
2024-11-26 00:52:31: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:52:31] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 201 -
2024-11-26 00:52:43: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:52:43] "[33mOPTIONS /api/v1/users/ HTTP/1.1[0m" 404 -
2024-11-26 00:54:38: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:54:38] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:54:38: INFO [users_routes.py:276] New User created: {'email': 'somesome@test.com', 'password': 'editUserReq1', 'type': 'client', 'status': 'active', '_id': 34}
2024-11-26 00:54:38: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:54:38] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 201 -
2024-11-26 00:55:57: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-26 00:55:57: INFO [users_model.py:58] MongoDB connection closed
2024-11-26 00:55:58: INFO [_internal.py:97]  * Restarting with stat
2024-11-26 00:55:58: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-26 00:55:58: WARNING [_internal.py:97]  * Debugger is active!
2024-11-26 00:55:58: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-26 00:56:00: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-26 00:56:00: INFO [users_model.py:58] MongoDB connection closed
2024-11-26 00:56:00: INFO [_internal.py:97]  * Restarting with stat
2024-11-26 00:56:01: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-26 00:56:01: WARNING [_internal.py:97]  * Debugger is active!
2024-11-26 00:56:01: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-26 00:56:03: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-26 00:56:03: INFO [users_model.py:58] MongoDB connection closed
2024-11-26 00:56:03: INFO [_internal.py:97]  * Restarting with stat
2024-11-26 00:56:03: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-26 00:56:03: WARNING [_internal.py:97]  * Debugger is active!
2024-11-26 00:56:03: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-26 00:56:04: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-26 00:56:04: INFO [users_model.py:58] MongoDB connection closed
2024-11-26 00:56:05: INFO [_internal.py:97]  * Restarting with stat
2024-11-26 00:56:05: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-26 00:56:05: WARNING [_internal.py:97]  * Debugger is active!
2024-11-26 00:56:05: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-26 00:56:21: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:56:21] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:56:21: ERROR [logger_base.py:29] Invalid user data: Password should have at least one numeral
2024-11-26 00:56:21: ERROR [logger_base.py:29] Error creating new user: Invalid user data: Password should have at least one numeral
2024-11-26 00:56:21: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:56:21] "[31m[1mPOST /api/v1/users HTTP/1.1[0m" 400 -
2024-11-26 00:56:31: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:56:31] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 00:56:31: INFO [users_routes.py:276] New User created: {'email': 'somesome@some.co', 'password': 'New_user_created1', 'type': 'client', 'status': 'active', '_id': 35}
2024-11-26 00:56:31: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:56:31] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 201 -
2024-11-26 00:56:49: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:56:49] "[33mOPTIONS /api/v1/users/ HTTP/1.1[0m" 404 -
2024-11-26 00:57:10: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:57:10] "[33mOPTIONS /api/v1/users/ HTTP/1.1[0m" 404 -
2024-11-26 00:57:18: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:57:18] "[33mOPTIONS /api/v1/users/ HTTP/1.1[0m" 404 -
2024-11-26 00:58:54: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:58:54] "[33mOPTIONS /api/v1/users/undefined HTTP/1.1[0m" 404 -
2024-11-26 00:59:24: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:59:24] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 00:59:24: INFO [users_routes.py:176] Login user: {'_id': 19, 'email': 'pablo9@test.com', 'password': '6ea1634442bf3a853f350c0d5612742c99646d8ca922ea942382ba152b51f077', 'type': 'admin', 'status': 'active'}
2024-11-26 00:59:24: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:59:24] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 201 -
2024-11-26 00:59:32: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 00:59:32] "[33mOPTIONS /api/v1/users/undefined HTTP/1.1[0m" 404 -
2024-11-26 01:00:12: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-26 01:00:12: INFO [users_model.py:58] MongoDB connection closed
2024-11-26 01:00:13: INFO [_internal.py:97]  * Restarting with stat
2024-11-26 01:00:18: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-26 01:00:18: WARNING [_internal.py:97]  * Debugger is active!
2024-11-26 01:00:18: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-26 01:00:20: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-26 01:00:20: INFO [users_model.py:58] MongoDB connection closed
2024-11-26 01:00:20: INFO [_internal.py:97]  * Restarting with stat
2024-11-26 01:00:21: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-26 01:00:21: WARNING [_internal.py:97]  * Debugger is active!
2024-11-26 01:00:21: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-26 01:00:35: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:00:35] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 01:00:35: INFO [users_routes.py:176] Login user: {'_id': 19, 'email': 'pablo9@test.com', 'password': '6ea1634442bf3a853f350c0d5612742c99646d8ca922ea942382ba152b51f077', 'type': 'admin', 'status': 'active'}
2024-11-26 01:00:35: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:00:35] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 201 -
2024-11-26 01:00:44: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:00:44] "[33mOPTIONS /api/v1/users/undefined HTTP/1.1[0m" 404 -
2024-11-26 01:01:56: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:01:56] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 01:01:56: INFO [users_routes.py:176] Login user: {'_id': 19, 'email': 'pablo9@test.com', 'password': '6ea1634442bf3a853f350c0d5612742c99646d8ca922ea942382ba152b51f077', 'type': 'admin', 'status': 'active'}
2024-11-26 01:01:56: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:01:56] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 201 -
2024-11-26 01:02:02: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:02:02] "OPTIONS /api/v1/users/19 HTTP/1.1" 200 -
2024-11-26 01:02:02: INFO [users_routes.py:382] User updated: {'_id': 19, 'email': 'pablo9@test.coma', 'password': 'passWord123', 'type': None}
2024-11-26 01:02:02: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:02:02] "PUT /api/v1/users/19 HTTP/1.1" 200 -
2024-11-26 01:02:41: INFO [_internal.py:97]  * Detected change in '/Users/pabloreyes/Documents/DS_UNAM/proyects/backend-project/users_API/routes/users_routes.py', reloading
2024-11-26 01:02:41: INFO [users_model.py:58] MongoDB connection closed
2024-11-26 01:02:41: INFO [_internal.py:97]  * Restarting with stat
2024-11-26 01:02:42: INFO [users_model.py:58] MongoDB connection closed
2024-11-26 01:02:52: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-26 01:02:52: INFO [_internal.py:97] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-11-26 01:02:52: INFO [_internal.py:97] [33mPress CTRL+C to quit[0m
2024-11-26 01:02:52: INFO [_internal.py:97]  * Restarting with stat
2024-11-26 01:02:53: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-26 01:02:53: WARNING [_internal.py:97]  * Debugger is active!
2024-11-26 01:02:53: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-26 01:02:56: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:02:56] "OPTIONS /api/v1/users/19 HTTP/1.1" 200 -
2024-11-26 01:02:56: INFO [users_routes.py:382] User updated: {'_id': 19, 'email': 'pablo9@test.coma', 'password': 'passWord123', 'type': None}
2024-11-26 01:02:56: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:02:56] "PUT /api/v1/users/19 HTTP/1.1" 200 -
2024-11-26 01:03:01: INFO [users_routes.py:382] User updated: {'_id': 19, 'email': 'pablo9@test.coma', 'password': 'passWord123', 'type': None}
2024-11-26 01:03:01: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:03:01] "PUT /api/v1/users/19 HTTP/1.1" 200 -
2024-11-26 01:03:18: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:03:18] "OPTIONS /api/v1/users/19 HTTP/1.1" 200 -
2024-11-26 01:03:18: INFO [users_routes.py:382] User updated: {'_id': 19, 'email': 'pablo9@test.coma', 'password': 'passWord123', 'type': None}
2024-11-26 01:03:18: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:03:18] "PUT /api/v1/users/19 HTTP/1.1" 200 -
2024-11-26 01:05:00: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:05:00] "OPTIONS /api/v1/users/19 HTTP/1.1" 200 -
2024-11-26 01:05:00: INFO [users_routes.py:382] User updated: {'_id': 19, 'email': 'pablo9@test.coma', 'password': 'passWord123', 'type': None}
2024-11-26 01:05:00: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:05:00] "PUT /api/v1/users/19 HTTP/1.1" 200 -
2024-11-26 01:07:06: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:07:06] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 01:07:06: ERROR [logger_base.py:29] Error: No user with the entered data was found.
2024-11-26 01:07:06: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:07:06] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 500 -
2024-11-26 01:07:10: INFO [users_routes.py:176] Login user: {'_id': 19, 'email': 'pablo9@test.coma', 'password': '6ea1634442bf3a853f350c0d5612742c99646d8ca922ea942382ba152b51f077', 'status': 'active', 'type': 'admin'}
2024-11-26 01:07:10: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:07:10] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 201 -
2024-11-26 01:07:15: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:07:15] "OPTIONS /api/v1/users/19 HTTP/1.1" 200 -
2024-11-26 01:07:15: INFO [users_routes.py:382] User updated: {'_id': 19, 'email': 'pablo9@test.com', 'password': 'passWord123', 'type': None}
2024-11-26 01:07:15: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:07:15] "PUT /api/v1/users/19 HTTP/1.1" 200 -
2024-11-26 01:08:21: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:08:21] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 01:08:21: INFO [users_routes.py:176] Login user: {'_id': 19, 'email': 'pablo9@test.com', 'password': '6ea1634442bf3a853f350c0d5612742c99646d8ca922ea942382ba152b51f077', 'status': 'active', 'type': None}
2024-11-26 01:08:21: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:08:21] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 201 -
2024-11-26 01:08:29: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:08:29] "OPTIONS /api/v1/users/19 HTTP/1.1" 200 -
2024-11-26 01:08:29: INFO [users_routes.py:382] User updated: {'_id': 19, 'email': 'pablo9@test.coma', 'password': 'passWord123', 'type': None}
2024-11-26 01:08:29: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:08:29] "PUT /api/v1/users/19 HTTP/1.1" 200 -
2024-11-26 01:09:37: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:09:37] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 01:09:37: ERROR [logger_base.py:29] Error: No user with the entered data was found.
2024-11-26 01:09:37: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:09:37] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 500 -
2024-11-26 01:09:41: INFO [users_routes.py:176] Login user: {'_id': 19, 'email': 'pablo9@test.coma', 'password': '6ea1634442bf3a853f350c0d5612742c99646d8ca922ea942382ba152b51f077', 'status': 'active', 'type': 'admin'}
2024-11-26 01:09:41: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:09:41] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 201 -
2024-11-26 01:09:50: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:09:50] "OPTIONS /api/v1/users/19 HTTP/1.1" 200 -
2024-11-26 01:09:50: INFO [users_routes.py:382] User updated: {'_id': 19, 'email': 'pablo9@test.com', 'password': 'passWord123', 'type': 'admin'}
2024-11-26 01:09:50: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:09:50] "PUT /api/v1/users/19 HTTP/1.1" 200 -
2024-11-26 01:10:08: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:10:08] "OPTIONS /api/v1/is-users HTTP/1.1" 200 -
2024-11-26 01:10:08: INFO [users_routes.py:176] Login user: {'_id': 19, 'email': 'pablo9@test.com', 'password': '6ea1634442bf3a853f350c0d5612742c99646d8ca922ea942382ba152b51f077', 'status': 'active', 'type': 'admin'}
2024-11-26 01:10:08: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:10:08] "[35m[1mPOST /api/v1/is-users HTTP/1.1[0m" 201 -
2024-11-26 01:13:26: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:13:26] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 01:13:26: ERROR [logger_base.py:29] Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 01:13:26: ERROR [logger_base.py:29] Error creating new user: Invalid user data: The email address is not valid. User email must have email format (user_name@domain)
2024-11-26 01:13:26: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:13:26] "[31m[1mPOST /api/v1/users HTTP/1.1[0m" 400 -
2024-11-26 01:13:31: ERROR [logger_base.py:29] Invalid user data: Password should have at least one uppercase letter
2024-11-26 01:13:31: ERROR [logger_base.py:29] Error creating new user: Invalid user data: Password should have at least one uppercase letter
2024-11-26 01:13:31: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:13:31] "[31m[1mPOST /api/v1/users HTTP/1.1[0m" 400 -
2024-11-26 01:13:37: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:13:37] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 01:13:37: ERROR [logger_base.py:29] Error adding new user to database: Email is already registered
2024-11-26 01:13:37: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:13:37] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 500 -
2024-11-26 01:13:42: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:13:42] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 01:13:42: INFO [users_routes.py:277] New User created: {'email': 'armando2@test.com', 'password': 'Armando1@test.com', 'type': 'client', 'status': 'active', '_id': 36}
2024-11-26 01:13:42: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:13:42] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 201 -
2024-11-26 01:13:53: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:13:53] "OPTIONS /api/v1/users/36 HTTP/1.1" 200 -
2024-11-26 01:13:53: INFO [users_routes.py:382] User updated: {'_id': 36, 'email': 'armando3@test.com', 'password': 'Armando1@test.com', 'type': 'client'}
2024-11-26 01:13:53: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:13:53] "PUT /api/v1/users/36 HTTP/1.1" 200 -
2024-11-26 01:13:57: INFO [users_routes.py:456] User deleted: {'_id': 36, 'email': 'armando3@test.com', 'password': '17edac4b5cf646201e53ac7a572e03fb51062d72f9fdd6322b7dbe3dd5f1342c', 'type': 'client', 'status': 'active'}
2024-11-26 01:13:57: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:13:57] "DELETE /api/v1/users/36 HTTP/1.1" 200 -
2024-11-26 01:14:21: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:14:21] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 01:14:21: INFO [users_routes.py:277] New User created: {'email': 'armando2@test.com', 'password': 'Armando1@test.com', 'type': 'client', 'status': 'active', '_id': 36}
2024-11-26 01:14:21: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:14:21] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 201 -
2024-11-26 01:14:38: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:14:38] "OPTIONS /api/v1/users/36 HTTP/1.1" 200 -
2024-11-26 01:14:38: INFO [users_routes.py:382] User updated: {'_id': 36, 'email': 'armando2@test.comAS', 'password': 'Armando1@test.com', 'type': 'client'}
2024-11-26 01:14:38: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:14:38] "PUT /api/v1/users/36 HTTP/1.1" 200 -
2024-11-26 01:14:47: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:14:47] "OPTIONS /api/v1/users/36 HTTP/1.1" 200 -
2024-11-26 01:14:47: INFO [users_routes.py:456] User deleted: {'_id': 36, 'email': 'armando2@test.comAS', 'password': '17edac4b5cf646201e53ac7a572e03fb51062d72f9fdd6322b7dbe3dd5f1342c', 'type': 'client', 'status': 'active'}
2024-11-26 01:14:47: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:14:47] "DELETE /api/v1/users/36 HTTP/1.1" 200 -
2024-11-26 01:18:38: INFO [users_model.py:58] MongoDB connection closed
2024-11-26 01:18:39: INFO [users_model.py:58] MongoDB connection closed
2024-11-26 01:32:03: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-26 01:32:03: INFO [_internal.py:97] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-11-26 01:32:03: INFO [_internal.py:97] [33mPress CTRL+C to quit[0m
2024-11-26 01:32:03: INFO [_internal.py:97]  * Restarting with stat
2024-11-26 01:32:03: INFO [users_model.py:48] Connected to MongoDB successfully
2024-11-26 01:32:03: WARNING [_internal.py:97]  * Debugger is active!
2024-11-26 01:32:03: INFO [_internal.py:97]  * Debugger PIN: 807-027-925
2024-11-26 01:32:25: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:32:25] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 01:32:25: ERROR [logger_base.py:29] Invalid user data: Password should have at least one uppercase letter
2024-11-26 01:32:25: ERROR [logger_base.py:29] Error creating new user: Invalid user data: Password should have at least one uppercase letter
2024-11-26 01:32:25: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:32:25] "[31m[1mPOST /api/v1/users HTTP/1.1[0m" 400 -
2024-11-26 01:32:38: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:32:38] "OPTIONS /api/v1/users HTTP/1.1" 200 -
2024-11-26 01:32:39: INFO [users_routes.py:277] New User created: {'email': 'Pablo91@test.coma', 'password': 'Pablo91@test.coma', 'type': 'client', 'status': 'active', '_id': 36}
2024-11-26 01:32:39: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:32:39] "[35m[1mPOST /api/v1/users HTTP/1.1[0m" 201 -
2024-11-26 01:32:51: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:32:51] "OPTIONS /api/v1/users/36 HTTP/1.1" 200 -
2024-11-26 01:32:51: INFO [users_routes.py:382] User updated: {'_id': 36, 'email': 'Pablo91@test.comaA', 'password': 'Pablo91@test.coma', 'type': 'client'}
2024-11-26 01:32:51: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:32:51] "PUT /api/v1/users/36 HTTP/1.1" 200 -
2024-11-26 01:32:53: INFO [users_routes.py:456] User deleted: {'_id': 36, 'email': 'Pablo91@test.comaA', 'password': 'd78374d743249b129a0b57b45017b06fc3369218f6a38b1d03dd588d0dabbd35', 'type': 'client', 'status': 'active'}
2024-11-26 01:32:53: INFO [_internal.py:97] 127.0.0.1 - - [26/Nov/2024 01:32:53] "DELETE /api/v1/users/36 HTTP/1.1" 200 -
2024-11-26 01:35:17: INFO [users_model.py:58] MongoDB connection closed
2024-11-26 01:35:17: INFO [users_model.py:58] MongoDB connection closed
